### ISSUE TITLE
Inquiry about whether the dataset can be shared

### ISSUE THREAD

**Issue by happygirlzt** [hyunji-Hong/Dicos-public#5]
Hi Hyunji,
Thank you very much for open-sourcing Dicos. I was wondering whether it is possible for you to share the dataset as well.
I used the SQL scripts you provided to BigQuery, however, it seems the free account cannot export all the data (limited to 1GB).
Specifically, I was looking for the sub-datasets which contains 668,520 SO posts, and 12,458 posts that were labeled as insecure by Dicos.

> 668,520 posts contained the change history. In the experiment, Dicos discovered 12,458 insecure posts (2%) with 14,719 insecure code snippets.

Please kindly suggest. Once again, thank you very much.

<img width="268" alt="Screenshot 2022-05-19 at 16 07 41" src="https://user-images.githubusercontent.com/15061984/169245278-3dec8e1b-236d-4fd2-9598-ddb57d6cee68.png">

**Comment by hyunji-Hong** [comment]
Hi @happygirlzt,
Thank you for your interest!

**Datasets can be downloaded from Google Bigquery via Google Cloud Storage (GCS) Bucket.** 
Since the whole dataset is huge, I think it would be better for you to download it directly from Google BigQuery rather than send it to you. 
For your better understanding, I leave a reference link on [how to download large datasets from BigQuery.](https://sql.info/d/how-to-export-table-data-to-a-file-in-google-bigquery)

We are also considering whether to disclose the results of insecure code snippet discovery. If we decide to make our results public, we plan to upload the discovery results to this repository.

Thanks, Hope this helps!

**Comment by happygirlzt** [comment]
Hi @hyunji-Hong, thank you very much for your reply! I will check it out. :)
> We are also considering whether to disclose the results of insecure code snippet discovery. If we decide to make our results public, we plan to upload the discovery results to this repository.

also thanks for the information. :)

**Comment by Alfusainey** [comment]
@hyunji-Hong 

> We are also considering whether to disclose the results of insecure code snippet discovery. If we decide to make our results public, we plan to upload the discovery results to this repository.

We're also interested in this. Were you (or your team) able to publish the discovered insecure code snippets to this repository? Or do you have security concerns in publishing your dataset of insecure code snippets?
